### ISSUE TITLE
Centralizar logo do portal na tela de login

### ISSUE THREAD

**Issue by oliveirabr** [LuizFelps/Gerencia-de-Configuracao-de-Software#2]
A logo do portal na tela de login se encontra alinhada à esquerda, quando deveria estar alinhada no centro.

Para solucionar o problema é necessário adicionar as seguintes classes do tailwindcss "flex items-center justify-center" ao elemento que contém a logo.

**Comment by Awdren** [comment]
Oi, @LuizFelps e @oliveirabr poderiam, por favor, colocar uma evidência que demonstre o alinhamento à esquerda?

Há também possibilidade de usando as ferramentas do desenvolvedor, no navegador, de fazer uma solução de ajuste... Poderiam printar e colocar aqui?

**Comment by oliveirabr** [comment]
> Oi, @LuizFelps e @oliveirabr poderiam, por favor, colocar uma evidência que demonstre o alinhamento à esquerda?
> 
> Há também possibilidade de usando as ferramentas do desenvolvedor, no navegador, de fazer uma solução de ajuste... Poderiam printar e colocar aqui?

Oi professor, essa foi uma issue fictícia que eu criei durante a aula, ainda vou criar as minhas issues verdadeiras.
